In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [3]:
#Unimos los dataframes en uno solo
nombres = ['01','02','03','04','05','06','07','08','09','10','11','12']
lista_df = []
for i in range(12):
    a = pd.read_csv(nombres[i]+".csv",  encoding='latin1')
    a.reset_index(drop=True, inplace=True)
    lista_df.append(a)
df = pd.concat(lista_df)
df

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,ï»¿Trip Id
0,10644218.0,1315,7021,01/01/2021 00:04,Bay St / Albert St,7164.0,01/01/2021 00:26,Gould St / Yonge St (Ryerson University),6795.0,Annual Member,NaN
1,10644220.0,396,7534,01/01/2021 00:07,Walnut Ave / Queen St W,7524.0,01/01/2021 00:13,Lisgar Park,4176.0,Casual Member,NaN
2,10644221.0,86,7162,01/01/2021 00:10,Hayter St / Laplante Ave,7006.0,01/01/2021 00:11,Bay St / College St (East Side),1814.0,Annual Member,NaN
3,10644222.0,741,7003,01/01/2021 00:10,Madison Ave / Bloor St W,7272.0,01/01/2021 00:22,Yonge St / Dundonald St - SMART,198.0,Casual Member,NaN
4,10644223.0,2073,7562,01/01/2021 00:11,Priscilla Ave / Dundas St W - SMART,7562.0,01/01/2021 00:45,Priscilla Ave / Dundas St W - SMART,6688.0,Casual Member,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145844,NaN,372,7065,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,3487.0,Casual Member,14805103.0
145845,NaN,762,7233,12/31/2021 23:56,King / Cowan Ave - SMART,7569.0,01/01/2022 00:08,Toronto Inukshuk Park,4195.0,Annual Member,14805104.0
145846,NaN,355,7065,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,4574.0,Casual Member,14805105.0
145847,NaN,770,7292,12/31/2021 23:56,Granby St / Church St - SMART,7076.0,01/01/2022 00:09,York St / Queens Quay W,5879.0,Annual Member,14805107.0
145848,NaN,1307,7057,12/31/2021 23:59,Simcoe St / Wellington St South,7383.0,01/01/2022 00:21,12 Harbour St,1655.0,Annual Member,14805108.0

In [4]:
#Eliminaremos las columnas con datos innecesarios 
df.pop('End Time')
df.pop('End Station Id')
df.pop('Start Station Id')
df.pop('Bike Id')
df.pop('User Type')
df.pop('Trip Id')
df.pop('ï»¿Trip Id')
df

,Trip Duration,Start Time,Start Station Name,End Station Name
0,1315,01/01/2021 00:04,Bay St / Albert St,Gould St / Yonge St (Ryerson University)
1,396,01/01/2021 00:07,Walnut Ave / Queen St W,Lisgar Park
2,86,01/01/2021 00:10,Hayter St / Laplante Ave,Bay St / College St (East Side)
3,741,01/01/2021 00:10,Madison Ave / Bloor St W,Yonge St / Dundonald St - SMART
4,2073,01/01/2021 00:11,Priscilla Ave / Dundas St W - SMART,Priscilla Ave / Dundas St W - SMART
...,...,...,...,...
145844,372,12/31/2021 23:56,Dundas St E / Parliament St,Dundas St E / Victoria St
145845,762,12/31/2021 23:56,King / Cowan Ave - SMART,Toronto Inukshuk Park
145846,355,12/31/2021 23:56,Dundas St E / Parliament St,Dundas St E / Victoria St
145847,770,12/31/2021 23:56,Granby St / Church St - SMART,York St / Queens Quay W
145848,1307,12/31/2021 23:59,Simcoe St / Wellington St South,12 Harbour St

In [5]:
#Separamos fecha y hora en columnas
df['date'] = pd.to_datetime(df['Start Time'])
df['hora'] = df['date'].dt.hour
df['fecha'] = df['date'].dt.date
df['dia'] = df['date'].dt.day 
df['mes']= df['date'].dt.month
df['dia de semana'] = df['date'].dt.day_name()
#Limpieza final
df.pop('Start Time')
df.pop('date')

0        2021-01-01 00:04:00
1        2021-01-01 00:07:00
2        2021-01-01 00:10:00
3        2021-01-01 00:10:00
4        2021-01-01 00:11:00
                 ...
145844   2021-12-31 23:56:00
145845   2021-12-31 23:56:00
145846   2021-12-31 23:56:00
145847   2021-12-31 23:56:00
145848   2021-12-31 23:59:00
Name: date, Length: 3575182, dtype: datetime64[ns]

In [6]:
#Dataframe final
df

,Trip Duration,Start Station Name,End Station Name,hora,fecha,dia,mes,dia de semana
0,1315,Bay St / Albert St,Gould St / Yonge St (Ryerson University),0,2021-01-01,1,1,Friday
1,396,Walnut Ave / Queen St W,Lisgar Park,0,2021-01-01,1,1,Friday
2,86,Hayter St / Laplante Ave,Bay St / College St (East Side),0,2021-01-01,1,1,Friday
3,741,Madison Ave / Bloor St W,Yonge St / Dundonald St - SMART,0,2021-01-01,1,1,Friday
4,2073,Priscilla Ave / Dundas St W - SMART,Priscilla Ave / Dundas St W - SMART,0,2021-01-01,1,1,Friday
...,...,...,...,...,...,...,...,...
145844,372,Dundas St E / Parliament St,Dundas St E / Victoria St,23,2021-12-31,31,12,Friday
145845,762,King / Cowan Ave - SMART,Toronto Inukshuk Park,23,2021-12-31,31,12,Friday
145846,355,Dundas St E / Parliament St,Dundas St E / Victoria St,23,2021-12-31,31,12,Friday
145847,770,Granby St / Church St - SMART,York St / Queens Quay W,23,2021-12-31,31,12,Friday
145848,1307,Simcoe St / Wellington St South,12 Harbour St,23,2021-12-31,31,12,Friday